### ISSUE TITLE
Breaks PDF rendering in Insider 1.3.0

### ISSUE THREAD

**Issue by hsiktas** [Phantom1003/obsidian-slide-note#5]
With the new PDF viewer in Insider 1.3.0, enabling this plugin breaks that functionality. PDFs now open in a blank window, and disabling this plugin fixes that issue again (after a restart).

**Comment by Phantom1003** [comment]
Sorry, I do not have access to the insider builds.
Do you get any error information?

**Comment by hsiktas** [comment]
Enabling the plugin and trying to open a PDF in my vault shows this in the console:

```
plugin:slide-note:105825 SlideNote loading ...
pdf.viewer.min.js:22 pdf.loading_error

PDF.js v3.6.0 (build: ?)
Message: The API version "3.6.0" does not match the Worker version "3.2.146".
_otherError @ pdf.viewer.min.js:22
_documentError @ pdf.viewer.min.js:22
(anonymous) @ pdf.viewer.min.js:22
Promise.then (async)
(anonymous) @ pdf.viewer.min.js:22
Promise.then (async)
open @ pdf.viewer.min.js:22
i @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFile @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setViewState @ app.js:1
eval @ plugin:obsidian-excalidraw-plugin:19
r @ plugin:obsidian-excalidraw-plugin:19
eval @ plugin:obsidian-kanban:77
o @ plugin:obsidian-kanban:23
eval @ plugin:obsidian-hover-editor:18
E @ plugin:obsidian-hover-editor:14
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onFileClick @ app.js:1
s @ enhance.js:1
index.html:1 Uncaught (in promise) UnknownErrorException {message: 'The API version "3.6.0" does not match the Worker version "3.2.146".', name: 'UnknownErrorException', details: 'Error: The API version "3.6.0" does not match the Worker version "3.2.146".'}details: "Error: The API version \"3.6.0\" does not match the Worker version \"3.2.146\"."message: "The API version \"3.6.0\" does not match the Worker version \"3.2.146\"."name: "UnknownErrorException"[[Prototype]]: Errorconstructor: class UnknownErrorException[[Prototype]]: Error
    at BaseExceptionClosure (app://obsidian.md/lib/pdfjs/pdf.min.js:22:8943)
    at Object.defineProperty.value (app://obsidian.md/lib/pdfjs/pdf.min.js:22:9014)
    at __w_pdfjs_require__ (app://obsidian.md/lib/pdfjs/pdf.min.js:22:281199)
    at app://obsidian.md/lib/pdfjs/pdf.min.js:22:285480
    at app://obsidian.md/lib/pdfjs/pdf.min.js:22:285735
    at app://obsidian.md/lib/pdfjs/pdf.min.js:22:285766
    at webpackUniversalModuleDefinition (app://obsidian.md/lib/pdfjs/pdf.min.js:22:290)
    at app://obsidian.md/lib/pdfjs/pdf.min.js:22:294

```

**Comment by Phantom1003** [comment]
I upgrade the version of the pdfjs, can you manually install this [preview plugin](https://github.com/Phantom1003/obsidian-slide-note/releases/tag/pre-0.0.7)?

**Comment by Phantom1003** [comment]
Please check the 0.0.7, I switch Slide Note to Obsidian's built-in pdfjs and this problem should be solved.
